import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

//Things to add a item category, description, price, supplier info, min threshhold for pentential notification
//Features import and export csv and pdfs, pagination/scrolling, search and filter, item categories, and user authentication, and removal of not just one object

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
